### ISSUE TITLE
panic: "certificate signed by unknown authority"

### ISSUE THREAD

**Issue by niko** [progrium/termshare#8]
When starting termshare (linux 64bit) I get:

```
$ ./termshare
panic: Post https://termsha.re:443/d6ae880b-xxxx: x509: certificate signed by unknown authority

goroutine 1 [running]:
main.createSession()
    /Users/progrium/Projects/termshare/termshare.go:211 +0x45a
main.main()
    /Users/progrium/Projects/termshare/termshare.go:433 +0xf9

goroutine 3 [syscall]:
os/signal.loop()
    /usr/local/Cellar/go/1.1.2/libexec/src/pkg/os/signal/signal_unix.go:21 +0x1c
created by os/signal.init·1
    /usr/local/Cellar/go/1.1.2/libexec/src/pkg/os/signal/signal_unix.go:27 +0x2f
```

**Comment by Arno0x** [comment]
Same goes on Darwin (OSX).

**Comment by bruno-** [comment]
Hi, I get this one on OSX too

**Comment by slava-vishnyakov** [comment]
Currently this is going on on OS X

``` sh
➜  ~ termshare
panic: Post https://termsha.re:443/bd13b663-xxxx: x509: certificate has expired or is not yet valid
```
